"""add fz attributes

Revision ID: 1a3a6ec81014
Revises: 7a2b9d74cd2f
Create Date: 2023-08-15 13:47:19.305838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a3a6ec81014"
down_revision: Union[str, None] = "7a2b9d74cd2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("fz_is_admin", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("fz_email", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("fz_password", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "fz_password")
    op.drop_column("users", "fz_email")
    op.drop_column("users", "fz_is_admin")
    # ### end Alembic commands ###
