"""change password field name

Revision ID: a1e64e323dc5
Revises: 1a3a6ec81014
Create Date: 2023-08-15 14:00:31.867017

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1e64e323dc5"
down_revision: Union[str, None] = "1a3a6ec81014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("fz_generated_password", sa.String(length=100), nullable=True)
    )
    op.drop_column("users", "fz_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("fz_password", sa.VARCHAR(length=100), nullable=True))
    op.drop_column("users", "fz_generated_password")
    # ### end Alembic commands ###
