"""add_deeplink_actions

Revision ID: ec0491c08e5e
Revises: 4e29f775444c
Create Date: 2023-08-17 14:17:02.467575

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec0491c08e5e"
down_revision: Union[str, None] = "4e29f775444c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deeplink_actions",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("to_link", sa.Boolean(), nullable=True),
        sa.Column("fz_user_id", sa.String(length=100), nullable=True),
        sa.Column("to_create", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fz_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deeplink_actions")
    # ### end Alembic commands ###
