version: "3.9"
name: telegram_vpn_bot
services:
  bot:
    container_name: bot
    build:
      dockerfile: docker/Dockerfile_bot
      context: ./
    env_file:
      - .env
    environment:
      POSTGRES_HOST: pg
    volumes:
      - ./:/app
    depends_on:
      pg:
        condition: service_healthy

  site:
    container_name: site
    build:
      dockerfile: docker/Dockerfile_site
      context: ./
    env_file:
      - .env
    environment:
      DJ_DEBUG: False
      POSTGRES_HOST: pg
    volumes:
      - ./:/app
#    ports:
#      - "8000:8000"
    depends_on:
      nginx:
        condition: service_started
      pg:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine-slim
    ports:
      - "8888:8888"
    volumes:
      - ./frontend/static:/static
      - ./docker/nginx.conf:/etc/nginx/conf.d/site.conf
    restart: always

  pg:
    container_name: pg
    image: postgres:14-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5
