FROM python:3.10.12-slim-bookworm
LABEL authors="Андрей Сильных"

RUN pip install --upgrade pip "poetry==1.5.1"
RUN poetry config virtualenvs.create false --local

COPY ../poetry.lock pyproject.toml ./

RUN poetry install --no-ansi --only main
ENV PYTYHONBUFFERED=1
ENTRYPOINT ["bash", "app/docker/docker-entrypoint_bot.sh"]
